apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: test
  labels:
    app: my-app
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-deployment
      labels:
        app: my-app
    spec:
      containers:
        - name: myapp-container
          image: nginx:1.21.3
  selector:
    matchLabels:
      app: my-app
          